### PR TITLE
Repository Overhaul

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Update Description**

  `Host a website on your Arduino.`

  <br>

- **Choose A License**

  **⤷** *https://choosealicense.com/licenses/*

  <br>

- ***[Disable Unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`

  <br>

- ***[Disable Unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`

<br>
<br>

## ![Badge Changes]

- General formatting / spacing

- Added license badge placeholder

- Formatted & refactored code

  - Compiles without errors

  - Had to structure it worse since 
    you are using the Arduino IDE.

    - WebArd.ino in `/Source/WebArd/` instead of just `/Source/`
    - `.cpp` files in `/src/` instead of something well named

    *If you care enough, you might*
    *wanna consider PlatformIO.*

    *It works best with VSCode,..*

    *It also allows to specify custom include / source paths.*

  - If you have questions in regards
    to the refactored code, let me know.

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/WebArd

### CODE REVIEW

**Comment by Compute64bits** [comment]
Thanks you!

**Comment by ElectronicsArchiver** [comment]
Sorry, you wrote 'Thank you' but closed the PR instead?

I hope this was a mistake..

**Comment by Compute64bits** [comment]
I'm not a github professional ^^'

**Comment by ElectronicsArchiver** [comment]
Well, pull requests are used to merge other 
peoples contributions into a project and 
thus acknowledging their contribution.

Copy pasting these contributions robs 
the contributor from their work, it's 
essentially stealing.

Since you didn't do it out of mallice,
I don't care, but now that you know,
please take care in the future.

You might want to watch a Youtube
video explaining the basics of
GitHub and the like~

**Comment by ElectronicsArchiver** [comment]
## PlatformIO

Btw, have you considered using PlatformIO
instead of the Arduino IDE, that way, the
code can be structured more cleanly.

*Besides many other things it brings*

*In specific I'm referring to using*
*VSCode + PlatformIO*

**Pull request closed without merging**
